### ISSUE TITLE
Typings Error when using Redux 4.0.0

### ISSUE THREAD

**Issue by kevinrjones** [angular-redux/ng-redux#197]
I'm completely new to Redux and angular/redux and don't know if you are support Redux 4.0.0 yet but I'm seeing an issue when using 4.0.0

**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

Fails to compile

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Run ```ng new myapp```
add references in package.json to ```Redux 4.0.0``` and ```@angular-redux/store 7.1.1```
in app.module.ts add 
``` import { NgReduxModule } from "@angular-redux/store"; ```

run ```ng build``` and you get the following error

```
ERROR in node_modules/@angular-redux/store/lib/src/components/ng-redux.d.ts(37,14): error TS2416: Property 'dispatch' in type 'NgRedux<RootState>' is not assignable to the same property in base type 'ObservableStore<RootState>'.
  Type 'Dispatch<RootState>' is not assignable to type 'Dispatch<AnyAction>'.
    Type 'RootState' is not assignable to type 'AnyAction'.
node_modules/@angular-redux/store/lib/src/components/ng-redux.d.ts(37,33): error TS2344: Type 'RootState' does not satisfy the constraint 'Action<any>'.
node_modules/@angular-redux/store/lib/src/components/root-store.d.ts(18,24): error TS2344: Type 'RootState' does not satisfy the constraint 'Action<any>'.
```

**What is the expected behavior?**

It should compile

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

This is on Mac OSX

It works with Redux 3.7.2

**Comment by AntJanus** [comment]
@kevinrjones I think you're on the wrong repo. This repo is for the angular-redux/ng-redux library, you're looking for the [angular-redux/store](https://github.com/angular-redux/store).

**Comment by kevinrjones** [comment]
Ah, thanks
